name: Code Quality Checks

on:
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 mypy

      - name: Run black
        run: |
          black --check .

      - name: Run isort
        run: |
          isort --check-only .

      - name: Run flake8
        run: |
          flake8 .

      - name: Run mypy
        run: |
          mypy .
        if: ${{ inputs.use_mypy == 'true' }}

      - name: Merge Blocker
        run: exit 1
        if: failure()
